version: '3.4'

services:
  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    ports:
      - 9411:9411
    networks:
      - spring-network

  fornecedor-db:
    image: postgres:latest
    # restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: fornecedor
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - spring-network

  fornecedor-service:
    image: diogohumberto/fornecedor-service:latest
    # restart: always
    build:
      context: .
      dockerfile: fornecedor/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING.DATASOURCE.URL: jdbc:postgresql://fornecedor-db:5432/fornecedor
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: 123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - 8081:8081
    depends_on:
      - fornecedor-db
      - eureka-server
      - api-gateway
      - zipkin-server
    networks:
      - spring-network

  loja-service:
    image: diogohumberto/loja-service:latest
    # restart: always
    build:
      context: .
      dockerfile: loja/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
    ports:
      - 8080:8080
    depends_on:
      - eureka-server
      - api-gateway
      - zipkin-server
    networks:
      - spring-network

  eureka-server:
    image: diogohumberto/eureka-server:latest
    # restart: always
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    ports:
      - 8761:8761
    networks:
      - spring-network

  api-gateway:
    image: diogohumberto/api-gateway:latest
    # restart: always
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - 8765:8765
    depends_on:
      - eureka-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge