spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
      routes:
      - id: loja
        uri: lb://loja
        predicates:
         - Path=/loja/**
      - id: fornecedor
        uri: lb://fornecedor
        predicates:
         - Path=/fornecedor/**
      - id: openapi
        uri: lb://api-gateway
        predicates:
         - Path=/v3/api-docs/**
        filters:        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs          
  banner:
    location: classpath:/templates/banner.txt
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: 'true'
    register-with-eureka: 'true'
server:
  port: '8765'
