eureka:
  client:
    fetch-registry: 'false'
    register-with-eureka: 'false'
spring:
  application:
    name: naming-server
  banner:
    location: classpath:/templates/banner.txt
server:
  port: '8761'
