eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: 'true'
    register-with-eureka: 'true'
server:
  servlet:
    context-path: /fornecedor
  port: '8081'
spring:
  application:
    name: fornecedor
  banner:
    location: classpath:/templates/banner.txt
resilience4j:
  retry:
    instances:
      default:
        max-attempts: '3'
springdoc:
  api-docs:
    path: /v3/api-docs
  show-actuator: 'true'
