eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: 'true'
    register-with-eureka: 'true'
server:
  servlet:
    context-path: /fornecedor
  port: '8081'
spring:
  application:
    name: fornecedor
